@baseUrl = http://localhost:4010
@userId = 684bcd0ce13ad1bc843b41cb

### Получить пользователя по ID
GET {{baseUrl}}/api/users/{{userId}}
Accept: application/json

### Получить пользователей
GET {{baseUrl}}/api/users/all
Accept: application/json

###

### Создать пользователя
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "desin@example.com",
  "password": "12345678",
  "name": "Денис"
}

### Обновить пользователя
PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json

{
  "email": "sdasd@example.com",
  "password": "12345678",
  "name": "Андрей"
}

###
DELETE {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json