env: "production"

server:
  address: "0.0.0.0"
  port: "4020"

postgres:
  dsn: "postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}?sslmode=disable"
  timeout: "10s"
