version: "3.9"

services:
  gin.gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge