version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
