version: '3.8'

services:
  gin.user-svc.mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    restart: unless-stopped
    networks:
      - app-network

  gin.user-svc.mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - gin.user-svc.mongo
    restart: unless-stopped
    networks:
      - app-network

  gin.user-svc:
    build:
      context: .
    ports:
      - "4010:4010"
    depends_on:
      - gin.user-svc.mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
