version: '3.9'

services:
  payment-svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-svc
    ports:
      - "4030:4030"
    networks:
      - app-network

networks:
  app-network:
    external: true
